# Only what differs from chart/values.yaml.
image:
  repository: 708485767572.dkr.ecr.us-east-1.amazonaws.com/shopstream/storefront
  tag: 4cf5bbcabcce53746333abc9d8474fb2ad8d5111
replicas: 2
hpa: { enabled: true, min: 2, max: 6, targetCPU: 60 }
